function [ddx_eq,ddy_eq,ddtheta_eq] = find_dd_Inair(Lc,M,dtheta,f_X,f_Y,g,tau,theta)
%FIND_DD_INAIR
%    [DDX_EQ,DDY_EQ,DDTHETA_EQ] = FIND_DD_INAIR(LC,M,DTHETA,F_X,F_Y,G,TAU,THETA)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    22-May-2021 16:15:43

t2 = cos(theta);
t3 = sin(theta);
t4 = Lc.^2;
t5 = dtheta.^2;
t7 = 1.0./Lc;
t8 = 1.0./M;
t6 = t2.^2;
ddx_eq = t7.*t8.*(Lc.*f_X.*4.0+t3.*tau.*3.0-Lc.*f_X.*t6.*3.0+M.*t2.*t4.*t5-Lc.*f_Y.*t2.*t3.*3.0);
if nargout > 1
    ddy_eq = t7.*t8.*(Lc.*f_Y-t2.*tau.*3.0-Lc.*M.*g+Lc.*f_Y.*t6.*3.0+M.*t3.*t4.*t5-Lc.*f_X.*t2.*t3.*3.0);
end
if nargout > 2
    ddtheta_eq = (t8.*(tau+Lc.*f_X.*t3-Lc.*f_Y.*t2).*3.0)./t4;
end
