function [dtheta_After,dx_After,I_F_Y] = find_Status_After_Collision_Slides(I,Lc,dtheta_Before,dx_Before,dy_Before,m,myu,theta)
%FIND_STATUS_AFTER_COLLISION_SLIDES
%    [DTHETA_AFTER,DX_AFTER,I_F_Y] = FIND_STATUS_AFTER_COLLISION_SLIDES(I,LC,DTHETA_BEFORE,DX_BEFORE,DY_BEFORE,M,MYU,THETA)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    22-May-2021 18:29:44

t2 = cos(theta);
t3 = I.*2.0;
t4 = Lc.^2;
t5 = theta.*2.0;
t6 = t2.^2;
t7 = sin(t5);
t8 = m.*myu.*t4.*t7;
t9 = m.*t4.*t6.*2.0;
t10 = -t8;
t11 = t3+t9+t10;
t12 = 1.0./t11;
dtheta_After = t12.*(I.*dtheta_Before+Lc.*dy_Before.*m.*t2-Lc.*dy_Before.*m.*myu.*sin(theta)).*2.0;
if nargout > 1
    dx_After = t12.*(I.*dx_Before-(dx_Before.*t8)./2.0-I.*dy_Before.*myu+dx_Before.*m.*t4.*t6+I.*Lc.*dtheta_Before.*myu.*t2).*2.0;
end
if nargout > 2
    I_F_Y = I.*m.*t12.*(dy_Before-Lc.*dtheta_Before.*t2).*-2.0;
end
