function ddtheta = find_dd_Touch(Lc,M,g,tau,theta)
%FIND_DD_TOUCH
%    DDTHETA = FIND_DD_TOUCH(LC,M,G,TAU,THETA)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    22-May-2021 16:18:52

ddtheta = (1.0./Lc.^2.*(tau.*3.0-Lc.*M.*g.*cos(theta).*3.0))./(M.*4.0);
