function f_Y = find_F_Slides(Lc,M,dtheta,f_X,g,tau,theta)
%FIND_F_SLIDES
%    F_Y = FIND_F_SLIDES(LC,M,DTHETA,F_X,G,TAU,THETA)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    22-May-2021 18:42:36

t2 = cos(theta);
t3 = sin(theta);
t4 = dtheta.^2;
f_Y = M.*g+(t2.*(tau+Lc.*f_X.*t3-Lc.*M.*g.*t2+Lc.^2.*M.*t2.*t3.*t4).*3.0)./(Lc.*(t2.^2.*3.0+1.0))-Lc.*M.*t3.*t4;
