function [f_X,f_Y] = find_F_Touch(Lc,M,dtheta,g,tau,theta)
%FIND_F_TOUCH
%    [F_X,F_Y] = FIND_F_TOUCH(LC,M,DTHETA,G,TAU,THETA)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    22-May-2021 16:18:52

t2 = cos(theta);
t3 = sin(theta);
t4 = dtheta.^2;
t5 = tau.*3.0;
t6 = 1.0./Lc;
t7 = Lc.*M.*g.*t2.*3.0;
t8 = -t7;
t9 = t5+t8;
f_X = t3.*t6.*t9.*(-1.0./4.0)-Lc.*M.*t2.*t4;
if nargout > 1
    f_Y = M.*g+(t2.*t6.*t9)./4.0-Lc.*M.*t3.*t4;
end
