function [ddth1,ddth2] = find_ddth1_ddth2(Lc1,Lc2,M1,M2,dth1,dth2,g,tau1,tau2,th1,th2)
%FIND_DDTH1_DDTH2
%    [DDTH1,DDTH2] = FIND_DDTH1_DDTH2(LC1,LC2,M1,M2,DTH1,DTH2,G,TAU1,TAU2,TH1,TH2)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    19-May-2021 23:24:34

t2 = sin(th1);
t3 = sin(th2);
t4 = Lc1.^2;
t5 = Lc2.^2;
t6 = M1.*2.0;
t7 = M2.^2;
t8 = dth1.^2;
t9 = dth2.^2;
t10 = th1.*2.0;
t11 = th2.*2.0;
t12 = -th2;
t13 = -t11;
t14 = t12+th1;
t17 = t10+t12;
t15 = cos(t14);
t16 = sin(t14);
t18 = t10+t13;
t20 = sin(t17);
t19 = cos(t18);
t21 = sin(t18);
t22 = M2.*t19;
t23 = -t22;
t24 = M2+t6+t23;
t25 = 1.0./t24;
ddth1 = -(t25.*(Lc2.*tau1.*-2.0+Lc2.*tau2.*2.0+Lc1.*t15.*tau2.*2.0+Lc1.*Lc2.*M2.*g.*t2+Lc1.*Lc2.*g.*t2.*t6+Lc1.*M2.*t5.*t9.*t16.*2.0+Lc2.*M2.*t4.*t8.*t21+Lc1.*Lc2.*M2.*g.*sin(t13+th1)))./(Lc2.*t4);
if nargout > 1
    ddth2 = (t25.*(Lc1.*M2.*tau2.*2.0+Lc1.*t6.*tau2-Lc2.*M2.*t15.*tau1.*2.0+Lc2.*M2.*t15.*tau2.*2.0-Lc1.*Lc2.*g.*t3.*t7+Lc1.*Lc2.*g.*t7.*t20+Lc2.*t4.*t7.*t8.*t16.*2.0+Lc1.*t5.*t7.*t9.*t21-Lc1.*Lc2.*M1.*M2.*g.*t3+Lc1.*Lc2.*M1.*M2.*g.*t20+Lc2.*M2.*t4.*t6.*t8.*t16))./(Lc1.*M2.*t5);
end
