function Fx_in = find_Fx_in(Lc1,Lc2,M1,M2,dth1,dth2,g,tau1,tau2,th1,th2)
%FIND_FX_IN
%    FX_IN = FIND_FX_IN(LC1,LC2,M1,M2,DTH1,DTH2,G,TAU1,TAU2,TH1,TH2)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    19-May-2021 23:24:35

t2 = cos(th1);
t3 = cos(th2);
t4 = sin(th1);
t5 = sin(th2);
t6 = Lc1.^2;
t7 = Lc2.^2;
t8 = M2.^2;
t9 = dth1.^2;
t10 = dth2.^2;
t13 = Lc1.*Lc2.*M1.*2.0;
t11 = t2.^2;
t12 = t3.^2;
t17 = Lc1.*Lc2.*M2.*t2.*t3.*t4.*t5.*4.0;
t14 = Lc1.*Lc2.*M2.*t11.*2.0;
t15 = Lc1.*Lc2.*M2.*t12.*2.0;
t16 = Lc1.*Lc2.*M2.*t11.*t12.*4.0;
t19 = -t17;
t18 = -t16;
t20 = t13+t14+t15+t18+t19;
t21 = 1.0./t20;
Fx_in = -Lc1.*M2.*t4.*t9-Lc2.*M2.*t5.*t10+Lc1.*M1.*t3.*t21.*tau2.*2.0+Lc2.*M2.*t2.*t21.*tau1.*2.0+Lc1.*M2.*t3.*t21.*tau2.*2.0-Lc2.*M2.*t2.*t21.*tau2.*2.0-Lc1.*M2.*t3.*t11.*t21.*tau2.*2.0-Lc2.*M2.*t2.*t12.*t21.*tau1.*2.0+Lc2.*M2.*t2.*t12.*t21.*tau2.*2.0-Lc1.*M2.*t2.*t4.*t5.*t21.*tau2.*2.0-Lc2.*M2.*t3.*t4.*t5.*t21.*tau1.*2.0+Lc2.*M2.*t3.*t4.*t5.*t21.*tau2.*2.0+M2.*g.*t2.*t4.*t12.*t13.*t21+Lc2.*t4.*t6.*t8.*t9.*t11.*t21.*2.0+Lc2.*t4.*t6.*t8.*t9.*t12.*t21.*2.0+Lc1.*t5.*t7.*t8.*t10.*t11.*t21.*2.0+Lc1.*t5.*t7.*t8.*t10.*t12.*t21.*2.0+Lc1.*t2.*t3.^3.*t4.*t7.*t8.*t10.*t21.*4.0+Lc2.*t2.^3.*t3.*t5.*t6.*t8.*t9.*t21.*4.0-Lc1.*Lc2.*M1.*M2.*g.*t2.*t4.*t21.*2.0+Lc2.*M1.*M2.*t4.*t6.*t9.*t12.*t21.*2.0-Lc1.*t2.*t3.*t4.*t7.*t8.*t10.*t21.*4.0-Lc2.*t2.*t3.*t5.*t6.*t8.*t9.*t21.*4.0-Lc2.*t4.*t6.*t8.*t9.*t11.*t12.*t21.*4.0-Lc1.*t5.*t7.*t8.*t10.*t11.*t12.*t21.*4.0-Lc1.*Lc2.*M1.*M2.*g.*t3.*t5.*t11.*t21.*2.0-Lc2.*M1.*M2.*t2.*t3.*t5.*t6.*t9.*t21.*2.0;
end