function tau_Hip = find_Tau_Hip_Inair(ddth_Hip,dth_Hip,dth_Wrist,l_Body,l_Leg,m_Body,m_Leg,th_Hip)
%FIND_TAU_HIP_INAIR
%    TAU_HIP = FIND_TAU_HIP_INAIR(DDTH_HIP,DTH_HIP,DTH_WRIST,L_BODY,L_LEG,M_BODY,M_LEG,TH_HIP)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    29-May-2021 00:51:25

t2 = sin(th_Hip);
t3 = dth_Hip.^2;
t4 = dth_Wrist.^2;
t5 = l_Body.^2;
t6 = l_Leg.^2;
t7 = m_Body.^2;
t8 = m_Leg.^2;
t9 = th_Hip.*2.0;
t10 = sin(t9);
tau_Hip = (l_Body.*l_Leg.*m_Body.*m_Leg.*(ddth_Hip.*l_Body.*l_Leg.*t7.*8.0+ddth_Hip.*l_Body.*l_Leg.*t8.*8.0+t2.*t4.*t5.*t7.*6.0+t2.*t3.*t6.*t8.*6.0+t2.*t4.*t6.*t8.*6.0+ddth_Hip.*l_Body.*l_Leg.*m_Body.*m_Leg.*2.5e+1+dth_Hip.*dth_Wrist.*t2.*t6.*t8.*1.2e+1+m_Body.*m_Leg.*t2.*t3.*t6.*2.4e+1+m_Body.*m_Leg.*t2.*t4.*t5.*2.4e+1+m_Body.*m_Leg.*t2.*t4.*t6.*2.4e+1-ddth_Hip.*l_Body.*l_Leg.*m_Body.*m_Leg.*cos(t9).*9.0+dth_Hip.*dth_Wrist.*m_Body.*m_Leg.*t2.*t6.*4.8e+1+l_Body.*l_Leg.*m_Body.*m_Leg.*t3.*t10.*9.0+l_Body.*l_Leg.*m_Body.*m_Leg.*t4.*t10.*1.8e+1+dth_Hip.*dth_Wrist.*l_Body.*l_Leg.*m_Body.*m_Leg.*t10.*1.8e+1))./((m_Body+m_Leg).*(t5.*t7+t6.*t8+m_Body.*m_Leg.*t5.*4.0+m_Body.*m_Leg.*t6.*4.0+l_Body.*l_Leg.*m_Body.*m_Leg.*cos(th_Hip).*6.0).*2.4e+1);
