function [ddth_Wrist,ddth_Hip] = find_dd_Onbar(dth_Hip,dth_Wrist,g,l_Body,l_Leg,l_Wrist_Bar,m_Body,m_Leg,tau_Hip,th_Hip,th_Wrist)
%FIND_DD_ONBAR
%    [DDTH_WRIST,DDTH_HIP] = FIND_DD_ONBAR(DTH_HIP,DTH_WRIST,G,L_BODY,L_LEG,L_WRIST_BAR,M_BODY,M_LEG,TAU_HIP,TH_HIP,TH_WRIST)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    22-May-2021 01:57:38

t2 = cos(th_Hip);
t3 = sin(th_Hip);
t4 = sin(th_Wrist);
t5 = th_Hip+th_Wrist;
t6 = dth_Hip.^2;
t7 = dth_Wrist.^2;
t8 = l_Body.^2;
t9 = l_Leg.^2;
t10 = l_Wrist_Bar.^2;
t11 = th_Hip.*2.0;
t16 = 1.0./l_Leg;
t20 = l_Body.*l_Wrist_Bar.*m_Body.*1.2e+1;
t21 = l_Body.*l_Wrist_Bar.*m_Leg.*2.4e+1;
t12 = cos(t11);
t13 = t2.^2;
t14 = sin(t11);
t15 = sin(t5);
t17 = t5+th_Hip;
t19 = m_Body.*t8.*4.0;
t22 = m_Leg.*t8.*1.2e+1;
t23 = m_Body.*t10.*1.2e+1;
t24 = m_Leg.*t10.*1.2e+1;
t25 = -t20;
t26 = -t21;
t18 = sin(t17);
ddth_Wrist = -(t16.*(l_Leg.*tau_Hip.*2.4e+1+l_Body.*t2.*tau_Hip.*3.6e+1-l_Wrist_Bar.*t2.*tau_Hip.*3.6e+1-g.*l_Body.*l_Leg.*m_Body.*t4.*1.2e+1-g.*l_Body.*l_Leg.*m_Leg.*t4.*1.5e+1+g.*l_Body.*l_Leg.*m_Leg.*t18.*9.0+g.*l_Leg.*l_Wrist_Bar.*m_Body.*t4.*2.4e+1+g.*l_Leg.*l_Wrist_Bar.*m_Leg.*t4.*1.5e+1-g.*l_Leg.*l_Wrist_Bar.*m_Leg.*t18.*9.0-l_Body.*m_Leg.*t3.*t6.*t9.*1.2e+1-l_Body.*m_Leg.*t3.*t7.*t9.*1.2e+1-l_Leg.*m_Leg.*t7.*t8.*t14.*9.0-l_Leg.*m_Leg.*t7.*t10.*t14.*9.0+l_Wrist_Bar.*m_Leg.*t3.*t6.*t9.*1.2e+1+l_Wrist_Bar.*m_Leg.*t3.*t7.*t9.*1.2e+1-dth_Hip.*dth_Wrist.*l_Body.*m_Leg.*t3.*t9.*2.4e+1+dth_Hip.*dth_Wrist.*l_Wrist_Bar.*m_Leg.*t3.*t9.*2.4e+1+l_Body.*l_Leg.*l_Wrist_Bar.*m_Leg.*t7.*t14.*1.8e+1))./(m_Body.*t8.*8.0+m_Body.*t10.*2.4e+1+m_Leg.*t8.*1.5e+1+m_Leg.*t10.*1.5e+1-l_Body.*l_Wrist_Bar.*m_Body.*2.4e+1-l_Body.*l_Wrist_Bar.*m_Leg.*3.0e+1-m_Leg.*t8.*t12.*9.0-m_Leg.*t10.*t12.*9.0+l_Body.*l_Wrist_Bar.*m_Leg.*t12.*1.8e+1);
if nargout > 1
    t27 = l_Body.*l_Wrist_Bar.*m_Leg.*t13.*1.8e+1;
    t28 = m_Leg.*t8.*t13.*9.0;
    t29 = m_Leg.*t10.*t13.*9.0;
    t30 = -t28;
    t31 = -t29;
    t32 = t19+t22+t23+t24+t25+t26+t27+t30+t31;
    t33 = 1.0./t32;
    ddth_Hip = -t16.*t33.*(l_Leg.*2.0+l_Body.*t2.*3.0-l_Wrist_Bar.*t2.*3.0).*(g.*l_Body.*m_Body.*t4.*3.0+g.*l_Body.*m_Leg.*t4.*6.0+g.*l_Leg.*m_Leg.*t15.*3.0-g.*l_Wrist_Bar.*m_Body.*t4.*6.0-g.*l_Wrist_Bar.*m_Leg.*t4.*6.0+l_Body.*l_Leg.*m_Leg.*t3.*t6.*3.0-l_Leg.*l_Wrist_Bar.*m_Leg.*t3.*t6.*3.0+dth_Hip.*dth_Wrist.*l_Body.*l_Leg.*m_Leg.*t3.*6.0-dth_Hip.*dth_Wrist.*l_Leg.*l_Wrist_Bar.*m_Leg.*t3.*6.0)+(t33.*(tau_Hip.*1.2e+1+g.*l_Leg.*m_Leg.*t15.*6.0-l_Body.*l_Leg.*m_Leg.*t3.*t7.*6.0+l_Leg.*l_Wrist_Bar.*m_Leg.*t3.*t7.*6.0).*(m_Body.*t8+m_Body.*t10.*3.0+m_Leg.*t8.*3.0+m_Leg.*t9+m_Leg.*t10.*3.0-l_Body.*l_Wrist_Bar.*m_Body.*3.0-l_Body.*l_Wrist_Bar.*m_Leg.*6.0+l_Body.*l_Leg.*m_Leg.*t2.*3.0-l_Leg.*l_Wrist_Bar.*m_Leg.*t2.*3.0))./(m_Leg.*t9);
end
end