function [dth_Wrist_After,dth_Hip_After,dl_Wrist_Bar_After,I_N_Wrist_Bar] = find_Status_After_Collision(dl_Wrist_Bar_Before,dl_N_Wrist_Bar_Before,dth_Hip_Before,dth_Wrist_Before,l_Body,l_Leg,l_N_Wrist_Bar,l_Wrist_Bar,m_Body,m_Leg,myu,th_Hip)
%FIND_STATUS_AFTER_COLLISION
%    [DTH_WRIST_AFTER,DTH_HIP_AFTER,DL_WRIST_BAR_AFTER,I_N_WRIST_BAR] = FIND_STATUS_AFTER_COLLISION(DL_WRIST_BAR_BEFORE,DL_N_WRIST_BAR_BEFORE,DTH_HIP_BEFORE,DTH_WRIST_BEFORE,L_BODY,L_LEG,L_N_WRIST_BAR,L_WRIST_BAR,M_BODY,M_LEG,MYU,TH_HIP)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    23-May-2021 00:52:40

t2 = cos(th_Hip);
t3 = sin(th_Hip);
t4 = l_Body.^2;
t5 = l_N_Wrist_Bar.^2;
t6 = l_Wrist_Bar.^2;
t7 = m_Body.^2;
t8 = m_Leg.^2;
t9 = th_Hip.*2.0;
t16 = l_Body.*l_Wrist_Bar.*m_Body.*m_Leg.*9.0e+1;
t17 = l_Body.*l_N_Wrist_Bar.*m_Body.*m_Leg.*myu.*4.5e+1;
t18 = l_N_Wrist_Bar.*l_Wrist_Bar.*m_Body.*m_Leg.*myu.*6.0e+1;
t10 = cos(t9);
t11 = sin(t9);
t12 = l_Body.*l_Wrist_Bar.*t7.*4.8e+1;
t13 = l_Body.*l_Wrist_Bar.*t8.*2.4e+1;
t14 = m_Body.*m_Leg.*t4.*4.0e+1;
t15 = m_Body.*m_Leg.*t6.*6.0e+1;
t21 = -t16;
t22 = l_Body.*l_N_Wrist_Bar.*myu.*t7.*2.4e+1;
t23 = l_Body.*l_N_Wrist_Bar.*myu.*t8.*1.2e+1;
t24 = l_N_Wrist_Bar.*l_Wrist_Bar.*myu.*t7.*4.8e+1;
t25 = l_N_Wrist_Bar.*l_Wrist_Bar.*myu.*t8.*1.2e+1;
t26 = -t18;
t27 = t4.*t7.*1.6e+1;
t28 = t4.*t8.*1.2e+1;
t29 = t6.*t7.*4.8e+1;
t30 = t6.*t8.*1.2e+1;
t19 = -t12;
t20 = -t13;
t31 = -t24;
t32 = -t25;
t33 = l_Body.*l_Wrist_Bar.*m_Body.*m_Leg.*t10.*1.8e+1;
t34 = m_Body.*m_Leg.*t4.*t10.*1.2e+1;
t35 = l_Body.*l_N_Wrist_Bar.*m_Body.*m_Leg.*myu.*t10.*9.0;
t36 = m_Body.*m_Leg.*myu.*t4.*t11.*3.0;
t37 = l_Body.*l_Wrist_Bar.*m_Body.*m_Leg.*myu.*t11.*9.0;
t38 = -t34;
t39 = -t35;
t40 = -t37;
t41 = t14+t15+t17+t19+t20+t21+t22+t23+t26+t27+t28+t29+t30+t31+t32+t33+t36+t38+t39+t40;
t42 = 1.0./t41;
dth_Wrist_After = dth_Wrist_Before-dl_N_Wrist_Bar_Before.*t42.*(l_Body.*t7.*8.0+l_Body.*t8.*4.0-l_Wrist_Bar.*t7.*1.6e+1-l_Wrist_Bar.*t8.*4.0+l_Body.*m_Body.*m_Leg.*1.5e+1-l_Wrist_Bar.*m_Body.*m_Leg.*2.0e+1+l_N_Wrist_Bar.*myu.*t7.*1.6e+1+l_N_Wrist_Bar.*myu.*t8.*4.0+l_N_Wrist_Bar.*m_Body.*m_Leg.*myu.*2.0e+1-l_Body.*m_Body.*m_Leg.*t10.*3.0+l_Body.*m_Body.*m_Leg.*myu.*t11.*3.0).*3.0;
if nargout > 1
    dth_Hip_After = dth_Hip_Before+(dl_N_Wrist_Bar_Before.*t42.*(l_Body.*l_Leg.*t7.*8.0+l_Body.*l_Leg.*t8.*4.0-l_Leg.*l_Wrist_Bar.*t7.*1.6e+1-l_Leg.*l_Wrist_Bar.*t8.*4.0+t2.*t4.*t7.*4.0+l_Body.*l_Leg.*m_Body.*m_Leg.*1.8e+1-l_Leg.*l_Wrist_Bar.*m_Body.*m_Leg.*2.0e+1+l_Leg.*l_N_Wrist_Bar.*myu.*t7.*1.6e+1+l_Leg.*l_N_Wrist_Bar.*myu.*t8.*4.0-l_Body.*l_Wrist_Bar.*t2.*t7.*1.2e+1+m_Body.*m_Leg.*t2.*t4.*4.0+myu.*t3.*t4.*t7.*2.0+l_Leg.*l_N_Wrist_Bar.*m_Body.*m_Leg.*myu.*2.0e+1-l_Body.*l_Wrist_Bar.*m_Body.*m_Leg.*t2.*1.2e+1+l_Body.*l_N_Wrist_Bar.*myu.*t2.*t7.*1.2e+1+m_Body.*m_Leg.*myu.*t3.*t4.*8.0-l_Body.*l_Leg.*m_Body.*m_Leg.*t2.^2.*6.0+l_Body.*l_Leg.*m_Body.*m_Leg.*myu.*t11.*3.0+l_Body.*l_N_Wrist_Bar.*m_Body.*m_Leg.*myu.*t2.*1.2e+1).*3.0)./l_Leg;
end
if nargout > 2
    dl_Wrist_Bar_After = dl_Wrist_Bar_Before-dl_N_Wrist_Bar_Before.*t42.*(l_Body.*l_N_Wrist_Bar.*t7.*2.4e+1+l_Body.*l_N_Wrist_Bar.*t8.*1.2e+1-l_N_Wrist_Bar.*l_Wrist_Bar.*t7.*4.8e+1-l_N_Wrist_Bar.*l_Wrist_Bar.*t8.*1.2e+1+myu.*t4.*t7.*4.0+myu.*t5.*t7.*4.8e+1+myu.*t5.*t8.*1.2e+1+l_Body.*l_N_Wrist_Bar.*m_Body.*m_Leg.*4.5e+1-l_N_Wrist_Bar.*l_Wrist_Bar.*m_Body.*m_Leg.*6.0e+1+m_Body.*m_Leg.*myu.*t4.*1.0e+1+m_Body.*m_Leg.*myu.*t5.*6.0e+1+m_Body.*m_Leg.*t4.*t11.*3.0-l_Body.*l_N_Wrist_Bar.*m_Body.*m_Leg.*t10.*9.0-l_Body.*l_Wrist_Bar.*m_Body.*m_Leg.*t11.*9.0-m_Body.*m_Leg.*myu.*t4.*t10.*6.0+l_Body.*l_N_Wrist_Bar.*m_Body.*m_Leg.*myu.*t11.*1.8e+1);
end
if nargout > 3
    I_N_Wrist_Bar = dl_N_Wrist_Bar_Before.*m_Body.*t4.*t42.*(t7.*8.0+t8.*8.0+m_Body.*m_Leg.*2.5e+1-m_Body.*m_Leg.*t10.*9.0).*(-1.0./2.0);
end
end