function [ddth_Wrist,ddth_Hip] = find_dd_Onbar_Debbug3(dth_Hip,dth_Wrist,l_Body,l_Leg,l_Wrist_Bar,m_Body,m_Leg,tau_Hip,th_Hip,th_Wrist)
%FIND_DD_ONBAR_DEBBUG3
%    [DDTH_WRIST,DDTH_HIP] = FIND_DD_ONBAR_DEBBUG3(DTH_HIP,DTH_WRIST,L_BODY,L_LEG,L_WRIST_BAR,M_BODY,M_LEG,TAU_HIP,TH_HIP,TH_WRIST)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    22-May-2021 00:13:07

t2 = cos(th_Hip);
t3 = sin(th_Hip);
t4 = sin(th_Wrist);
t5 = th_Hip+th_Wrist;
t6 = dth_Hip.^2;
t7 = dth_Wrist.^2;
t8 = l_Body.^2;
t9 = l_Leg.^2;
t10 = l_Wrist_Bar.^2;
t11 = th_Hip.*2.0;
t16 = 1.0./l_Leg;
t18 = l_Body.*l_Wrist_Bar.*m_Body.*4.0;
t25 = l_Body.*l_Wrist_Bar.*m_Leg.*8.0;
t12 = cos(t11);
t13 = t2.^2;
t14 = sin(t11);
t15 = sin(t5);
t17 = m_Body.*t8;
t19 = t5+th_Hip;
t21 = m_Leg.*t8.*4.0;
t22 = m_Body.*t10.*4.0;
t23 = m_Leg.*t10.*4.0;
t24 = -t18;
t26 = -t25;
t20 = sin(t19);
ddth_Wrist = -(t16.*(l_Leg.*tau_Hip.*4.0+l_Body.*t2.*tau_Hip.*8.0-l_Wrist_Bar.*t2.*tau_Hip.*8.0-l_Body.*l_Leg.*m_Body.*t4.*2.0-l_Body.*l_Leg.*m_Leg.*t4.*2.0+l_Body.*l_Leg.*m_Leg.*t20.*2.0+l_Leg.*l_Wrist_Bar.*m_Body.*t4.*4.0+l_Leg.*l_Wrist_Bar.*m_Leg.*t4.*2.0-l_Leg.*l_Wrist_Bar.*m_Leg.*t20.*2.0-l_Body.*m_Leg.*t3.*t6.*t9.*2.0-l_Body.*m_Leg.*t3.*t7.*t9.*2.0-l_Leg.*m_Leg.*t7.*t8.*t14.*2.0-l_Leg.*m_Leg.*t7.*t10.*t14.*2.0+l_Wrist_Bar.*m_Leg.*t3.*t6.*t9.*2.0+l_Wrist_Bar.*m_Leg.*t3.*t7.*t9.*2.0-dth_Hip.*dth_Wrist.*l_Body.*m_Leg.*t3.*t9.*4.0+dth_Hip.*dth_Wrist.*l_Wrist_Bar.*m_Leg.*t3.*t9.*4.0+l_Body.*l_Leg.*l_Wrist_Bar.*m_Leg.*t7.*t14.*4.0))./(t17+t22+t24+m_Leg.*t8.*2.0+m_Leg.*t10.*2.0-l_Body.*l_Wrist_Bar.*m_Leg.*4.0-m_Leg.*t8.*t12.*2.0-m_Leg.*t10.*t12.*2.0+l_Body.*l_Wrist_Bar.*m_Leg.*t12.*4.0);
if nargout > 1
    t27 = l_Leg.*m_Leg.*t15.*2.0;
    t28 = t13.*t21;
    t29 = t13.*t23;
    t30 = t13.*t25;
    t31 = m_Leg.*t8.*t13.*-4.0;
    t32 = m_Leg.*t10.*t13.*-4.0;
    t33 = t17+t21+t22+t23+t24+t26+t30+t31+t32;
    t34 = 1.0./t33;
    ddth_Hip = -t16.*t34.*(l_Leg+l_Body.*t2.*2.0-l_Wrist_Bar.*t2.*2.0).*(t27+l_Body.*m_Body.*t4.*2.0+l_Body.*m_Leg.*t4.*4.0-l_Wrist_Bar.*m_Body.*t4.*4.0-l_Wrist_Bar.*m_Leg.*t4.*4.0+l_Body.*l_Leg.*m_Leg.*t3.*t6.*2.0-l_Leg.*l_Wrist_Bar.*m_Leg.*t3.*t6.*2.0+dth_Hip.*dth_Wrist.*l_Body.*l_Leg.*m_Leg.*t3.*4.0-dth_Hip.*dth_Wrist.*l_Leg.*l_Wrist_Bar.*m_Leg.*t3.*4.0)+(t34.*(t27+tau_Hip.*4.0-l_Body.*l_Leg.*m_Leg.*t3.*t7.*2.0+l_Leg.*l_Wrist_Bar.*m_Leg.*t3.*t7.*2.0).*(t17+t21+t22+t23+t24+t26+m_Leg.*t9+l_Body.*l_Leg.*m_Leg.*t2.*4.0-l_Leg.*l_Wrist_Bar.*m_Leg.*t2.*4.0))./(m_Leg.*t9);
end
