function ang_M = find_Ang_M(dth_Hip,dth_Wrist,l_Body,l_Leg,m_Body,m_Leg,th_Hip)
%FIND_ANG_M
%    ANG_M = FIND_ANG_M(DTH_HIP,DTH_WRIST,L_BODY,L_LEG,M_BODY,M_LEG,TH_HIP)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    23-May-2021 16:31:15

t2 = cos(th_Hip);
t3 = l_Body.^2;
t4 = l_Leg.^2;
t5 = m_Leg.^2;
ang_M = (dth_Wrist.*m_Body.^2.*t3+dth_Hip.*t4.*t5+dth_Wrist.*t4.*t5+dth_Hip.*m_Body.*m_Leg.*t4.*4.0+dth_Wrist.*m_Body.*m_Leg.*t3.*4.0+dth_Wrist.*m_Body.*m_Leg.*t4.*4.0+dth_Hip.*l_Body.*l_Leg.*m_Body.*m_Leg.*t2.*3.0+dth_Wrist.*l_Body.*l_Leg.*m_Body.*m_Leg.*t2.*6.0)./(m_Body.*1.2e+1+m_Leg.*1.2e+1);
end