function [ddth_Wrist,ddth_Hip,ddx,ddy] = find_dd_Inair(dth_Hip,dth_Wrist,g,l_Body,l_Leg,m_Body,m_Leg,tau_Hip,th_Hip,th_Wrist)
%FIND_DD_INAIR
%    [DDTH_WRIST,DDTH_HIP,DDX,DDY] = FIND_DD_INAIR(DTH_HIP,DTH_WRIST,G,L_BODY,L_LEG,M_BODY,M_LEG,TAU_HIP,TH_HIP,TH_WRIST)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    23-May-2021 01:12:13

t2 = cos(th_Hip);
t3 = cos(th_Wrist);
t4 = sin(th_Hip);
t5 = sin(th_Wrist);
t6 = th_Hip+th_Wrist;
t7 = dth_Hip.^2;
t8 = dth_Wrist.^2;
t9 = l_Body.^2;
t10 = l_Body.^3;
t11 = l_Leg.^2;
t12 = l_Leg.^3;
t13 = m_Body.^2;
t14 = m_Body.^3;
t15 = m_Leg.^2;
t16 = m_Leg.^3;
t17 = th_Hip.*2.0;
t22 = 1.0./l_Body;
t24 = 1.0./l_Leg;
t25 = 1.0./m_Body;
t26 = -th_Wrist;
t27 = m_Body.*m_Leg.*2.5e+1;
t18 = cos(t17);
t19 = sin(t17);
t20 = cos(t6);
t21 = sin(t6);
t23 = 1.0./t9;
ddth_Wrist = (t23.*t24.*t25.*(l_Leg.*t13.*tau_Hip.*-4.8e+1-l_Leg.*t15.*tau_Hip.*1.2e+1-l_Leg.*m_Body.*m_Leg.*tau_Hip.*6.0e+1-l_Body.*t2.*t13.*tau_Hip.*3.6e+1-l_Body.*m_Body.*m_Leg.*t2.*tau_Hip.*3.6e+1+l_Body.*m_Body.*t4.*t7.*t11.*t15.*3.0+l_Body.*m_Body.*t4.*t8.*t11.*t15.*3.0+l_Body.*m_Leg.*t4.*t7.*t11.*t13.*1.2e+1+l_Body.*m_Leg.*t4.*t8.*t11.*t13.*1.2e+1+l_Leg.*m_Leg.*t8.*t9.*t13.*t19.*(9.0./2.0)+dth_Hip.*dth_Wrist.*l_Body.*m_Body.*t4.*t11.*t15.*6.0+dth_Hip.*dth_Wrist.*l_Body.*m_Leg.*t4.*t11.*t13.*2.4e+1))./(t13.*4.0+t15.*4.0+m_Body.*m_Leg.*1.7e+1-m_Body.*m_Leg.*t2.^2.*9.0);
if nargout > 1
    t28 = t6+th_Hip;
    t31 = t13.*8.0;
    t32 = t15.*8.0;
    t33 = t26+th_Hip;
    t29 = cos(t28);
    t30 = sin(t28);
    t34 = cos(t33);
    t35 = sin(t33);
    t36 = m_Body.*m_Leg.*t18.*9.0;
    t37 = -t36;
    t38 = t27+t31+t32+t37;
    t39 = 1.0./t38;
    ddth_Hip = (t23.*t25.*t39.*(t9.*t14.*tau_Hip.*-1.2e+1-t11.*t16.*tau_Hip.*1.2e+1-m_Body.*t9.*t15.*tau_Hip.*4.8e+1-m_Body.*t11.*t15.*tau_Hip.*6.0e+1-m_Leg.*t9.*t13.*tau_Hip.*6.0e+1-m_Leg.*t11.*t13.*tau_Hip.*4.8e+1-l_Body.*l_Leg.*m_Body.*t2.*t15.*tau_Hip.*7.2e+1-l_Body.*l_Leg.*m_Leg.*t2.*t13.*tau_Hip.*7.2e+1+l_Body.*m_Body.*t4.*t7.*t12.*t16.*3.0+l_Body.*m_Body.*t4.*t8.*t12.*t16.*3.0+l_Leg.*m_Leg.*t4.*t8.*t10.*t14.*3.0+l_Body.*t4.*t7.*t12.*t13.*t15.*1.2e+1+l_Body.*t4.*t8.*t12.*t13.*t15.*1.2e+1+l_Leg.*t4.*t8.*t10.*t13.*t15.*1.2e+1+t7.*t9.*t11.*t13.*t15.*t19.*(9.0./2.0)+t8.*t9.*t11.*t13.*t15.*t19.*9.0+dth_Hip.*dth_Wrist.*l_Body.*m_Body.*t4.*t12.*t16.*6.0+dth_Hip.*dth_Wrist.*l_Body.*t4.*t12.*t13.*t15.*2.4e+1+dth_Hip.*dth_Wrist.*t9.*t11.*t13.*t15.*t19.*9.0).*-2.0)./(m_Leg.*t11);
end
if nargout > 2
    ddx = -t22.*t24.*t25.*t39.*(l_Body.*t13.*t20.*tau_Hip.*6.0+l_Body.*t13.*t34.*tau_Hip.*1.8e+1+l_Leg.*t3.*t13.*tau_Hip.*4.8e+1+l_Leg.*t3.*t15.*tau_Hip.*2.4e+1-l_Body.*m_Body.*m_Leg.*t20.*tau_Hip.*1.2e+1+l_Body.*m_Body.*m_Leg.*t34.*tau_Hip.*3.6e+1+l_Leg.*m_Body.*m_Leg.*t3.*tau_Hip.*9.0e+1-l_Leg.*m_Body.*m_Leg.*t29.*tau_Hip.*1.8e+1+l_Leg.*t5.*t8.*t9.*t14.*4.0+l_Body.*m_Body.*t7.*t11.*t15.*t21+l_Body.*m_Body.*t8.*t11.*t15.*t21-l_Body.*m_Body.*t7.*t11.*t15.*t35.*3.0-l_Body.*m_Body.*t8.*t11.*t15.*t35.*3.0-l_Body.*m_Leg.*t7.*t11.*t13.*t21.*2.0-l_Body.*m_Leg.*t8.*t11.*t13.*t21.*2.0+l_Leg.*m_Body.*t5.*t8.*t9.*t32-l_Body.*m_Leg.*t7.*t11.*t13.*t35.*6.0-l_Body.*m_Leg.*t8.*t11.*t13.*t35.*6.0+l_Leg.*m_Leg.*t5.*t8.*t9.*t13.*1.5e+1-l_Leg.*m_Leg.*t8.*t9.*t13.*t30.*3.0+dth_Hip.*dth_Wrist.*l_Body.*m_Body.*t11.*t15.*t21.*2.0-dth_Hip.*dth_Wrist.*l_Body.*m_Body.*t11.*t15.*t35.*6.0-dth_Hip.*dth_Wrist.*l_Body.*m_Leg.*t11.*t13.*t21.*4.0-dth_Hip.*dth_Wrist.*l_Body.*m_Leg.*t11.*t13.*t35.*1.2e+1);
end
if nargout > 3
    ddy = t22.*t24.*t25.*t39.*(g.*l_Body.*l_Leg.*t14.*-8.0-l_Body.*t13.*t21.*tau_Hip.*6.0+l_Body.*t13.*t35.*tau_Hip.*1.8e+1-l_Leg.*t5.*t13.*tau_Hip.*4.8e+1-l_Leg.*t5.*t15.*tau_Hip.*2.4e+1-g.*l_Body.*l_Leg.*m_Body.*t15.*8.0-g.*l_Body.*l_Leg.*m_Leg.*t13.*2.5e+1+l_Body.*m_Body.*m_Leg.*t21.*tau_Hip.*1.2e+1+l_Body.*m_Body.*m_Leg.*t35.*tau_Hip.*3.6e+1-l_Leg.*m_Body.*m_Leg.*t5.*tau_Hip.*9.0e+1+l_Leg.*m_Body.*m_Leg.*t30.*tau_Hip.*1.8e+1+l_Leg.*t3.*t8.*t9.*t14.*4.0+l_Body.*m_Body.*t7.*t11.*t15.*t20+l_Body.*m_Body.*t8.*t11.*t15.*t20+l_Body.*m_Body.*t7.*t11.*t15.*t34.*3.0+l_Body.*m_Body.*t8.*t11.*t15.*t34.*3.0-l_Body.*m_Leg.*t7.*t11.*t13.*t20.*2.0-l_Body.*m_Leg.*t8.*t11.*t13.*t20.*2.0+l_Leg.*m_Body.*t3.*t8.*t9.*t32+l_Body.*m_Leg.*t7.*t11.*t13.*t34.*6.0+l_Body.*m_Leg.*t8.*t11.*t13.*t34.*6.0+l_Leg.*m_Leg.*t3.*t8.*t9.*t13.*1.5e+1-l_Leg.*m_Leg.*t8.*t9.*t13.*t29.*3.0+g.*l_Body.*l_Leg.*m_Leg.*t13.*t18.*9.0+dth_Hip.*dth_Wrist.*l_Body.*m_Body.*t11.*t15.*t20.*2.0+dth_Hip.*dth_Wrist.*l_Body.*m_Body.*t11.*t15.*t34.*6.0-dth_Hip.*dth_Wrist.*l_Body.*m_Leg.*t11.*t13.*t20.*4.0+dth_Hip.*dth_Wrist.*l_Body.*m_Leg.*t11.*t13.*t34.*1.2e+1);
end
end
