function f_Wrist_Bar = find_F_Wrist_Bar(ddl_Wrist_Bar,ddth_Hip,ddth_Wrist,dth_Hip,dth_Wrist,g,l_Body,l_Leg,l_Wrist_Bar,m_Body,m_Leg,th_Hip,th_Wrist)
%FIND_F_WRIST_BAR
%    F_WRIST_BAR = FIND_F_WRIST_BAR(DDL_WRIST_BAR,DDTH_HIP,DDTH_WRIST,DTH_HIP,DTH_WRIST,G,L_BODY,L_LEG,L_WRIST_BAR,M_BODY,M_LEG,TH_HIP,TH_WRIST)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    22-May-2021 02:11:35

t2 = dth_Hip.^2;
t3 = dth_Wrist.^2;
t4 = pi./2.0;
t5 = t4+th_Wrist;
t6 = cos(t5);
t7 = sin(t5);
t8 = t5+th_Hip;
t9 = cos(t8);
t10 = sin(t8);
t11 = t6.^2;
t12 = t7.^2;
f_Wrist_Bar = ddl_Wrist_Bar.*m_Body.*t11+ddl_Wrist_Bar.*m_Body.*t12+ddl_Wrist_Bar.*m_Leg.*t11+ddl_Wrist_Bar.*m_Leg.*t12-g.*m_Body.*t7-g.*m_Leg.*t7+(l_Body.*m_Body.*t3.*t11)./2.0+(l_Body.*m_Body.*t3.*t12)./2.0+l_Body.*m_Leg.*t3.*t11+l_Body.*m_Leg.*t3.*t12-l_Wrist_Bar.*m_Body.*t3.*t11-l_Wrist_Bar.*m_Body.*t3.*t12-l_Wrist_Bar.*m_Leg.*t3.*t11-l_Wrist_Bar.*m_Leg.*t3.*t12+(ddth_Hip.*l_Leg.*m_Leg.*t6.*t10)./2.0-(ddth_Hip.*l_Leg.*m_Leg.*t7.*t9)./2.0+(ddth_Wrist.*l_Leg.*m_Leg.*t6.*t10)./2.0-(ddth_Wrist.*l_Leg.*m_Leg.*t7.*t9)./2.0+(l_Leg.*m_Leg.*t2.*t6.*t9)./2.0+(l_Leg.*m_Leg.*t3.*t6.*t9)./2.0+(l_Leg.*m_Leg.*t2.*t7.*t10)./2.0+(l_Leg.*m_Leg.*t3.*t7.*t10)./2.0+dth_Hip.*dth_Wrist.*l_Leg.*m_Leg.*t6.*t9+dth_Hip.*dth_Wrist.*l_Leg.*m_Leg.*t7.*t10;
