function tau_Hip = find_Tau_Hip_Onbar(ddth_Hip,dth_Hip,dth_Wrist,g,l_Body,l_Leg,l_Wrist_Bar,m_Body,m_Leg,th_Hip,th_Wrist)
%FIND_TAU_HIP_ONBAR
%    TAU_HIP = FIND_TAU_HIP_ONBAR(DDTH_HIP,DTH_HIP,DTH_WRIST,G,L_BODY,L_LEG,L_WRIST_BAR,M_BODY,M_LEG,TH_HIP,TH_WRIST)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    29-May-2021 00:53:14

t2 = cos(th_Hip);
t3 = sin(th_Hip);
t4 = sin(th_Wrist);
t5 = th_Hip+th_Wrist;
t6 = dth_Hip.^2;
t7 = dth_Wrist.^2;
t8 = l_Body.^2;
t9 = l_Leg.^2;
t10 = l_Wrist_Bar.^2;
t11 = sin(t5);
tau_Hip = (l_Leg.*m_Leg.*(ddth_Hip.*l_Leg.*4.0-g.*t11.*6.0+l_Body.*t3.*t7.*6.0-l_Wrist_Bar.*t3.*t7.*3.0))./1.2e+1-(l_Leg.*l_Wrist_Bar.*m_Leg.*t3.*t7)./4.0-(l_Leg.*m_Leg.*(l_Leg.*2.0+l_Body.*t2.*3.0-l_Wrist_Bar.*t2.*3.0).*(ddth_Hip.*m_Leg.*t9.*2.0-g.*l_Body.*m_Body.*t4.*3.0-g.*l_Body.*m_Leg.*t4.*6.0-g.*l_Leg.*m_Leg.*t11.*3.0+g.*l_Wrist_Bar.*m_Body.*t4.*6.0+g.*l_Wrist_Bar.*m_Leg.*t4.*6.0+ddth_Hip.*l_Body.*l_Leg.*m_Leg.*t2.*3.0-ddth_Hip.*l_Leg.*l_Wrist_Bar.*m_Leg.*t2.*3.0-l_Body.*l_Leg.*m_Leg.*t3.*t6.*3.0+l_Leg.*l_Wrist_Bar.*m_Leg.*t3.*t6.*3.0-dth_Hip.*dth_Wrist.*l_Body.*l_Leg.*m_Leg.*t3.*6.0+dth_Hip.*dth_Wrist.*l_Leg.*l_Wrist_Bar.*m_Leg.*t3.*6.0))./(m_Body.*t8.*1.2e+1+m_Body.*t10.*3.6e+1+m_Leg.*t8.*3.6e+1+m_Leg.*t9.*1.2e+1+m_Leg.*t10.*3.6e+1-l_Body.*l_Wrist_Bar.*m_Body.*3.6e+1-l_Body.*l_Wrist_Bar.*m_Leg.*7.2e+1+l_Body.*l_Leg.*m_Leg.*t2.*3.6e+1-l_Leg.*l_Wrist_Bar.*m_Leg.*t2.*3.6e+1);
