function [ddl_Wrist_Bar,ddth_Wrist,ddth_Hip] = find_dd_Catch_Debbug(dl_Wrist_Bar,dth_Hip,dth_Wrist,f_Wrist_Bar,g,l_Body,l_Leg,l_Wrist_Bar,m_Body,m_Leg,tau_Hip,th_Hip,th_Wrist)
%FIND_DD_CATCH_DEBBUG
%    [DDL_WRIST_BAR,DDTH_WRIST,DDTH_HIP] = FIND_DD_CATCH_DEBBUG(DL_WRIST_BAR,DTH_HIP,DTH_WRIST,F_WRIST_BAR,G,L_BODY,L_LEG,L_WRIST_BAR,M_BODY,M_LEG,TAU_HIP,TH_HIP,TH_WRIST)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    22-May-2021 02:11:33

t2 = cos(th_Hip);
t3 = cos(th_Wrist);
t4 = sin(th_Hip);
t5 = sin(th_Wrist);
t6 = dth_Hip.^2;
t7 = dth_Wrist.^2;
t8 = l_Body.^2;
t9 = l_Body.^3;
t10 = l_Leg.^2;
t11 = l_Leg.^3;
t12 = l_Wrist_Bar.^2;
t13 = l_Wrist_Bar.^3;
t14 = m_Body.^2;
t15 = m_Leg.^2;
t16 = m_Leg.^3;
t17 = th_Hip.*2.0;
t21 = 1.0./l_Leg;
t23 = l_Body.*l_Wrist_Bar.*m_Body.*m_Leg.*2.7e+1;
t18 = cos(t17);
t19 = t2.^2;
t20 = sin(t17);
ddl_Wrist_Bar = (t21.*(f_Wrist_Bar.*l_Leg.*m_Body.*t8.*-1.6e+1-f_Wrist_Bar.*l_Leg.*m_Body.*t12.*4.8e+1-f_Wrist_Bar.*l_Leg.*m_Leg.*t8.*3.0e+1-f_Wrist_Bar.*l_Leg.*m_Leg.*t12.*3.0e+1+l_Leg.*t7.*t9.*t14.*8.0+l_Leg.*t7.*t9.*t15.*1.2e+1-l_Leg.*t7.*t13.*t14.*4.8e+1-l_Leg.*t7.*t13.*t15.*1.2e+1+m_Body.*t4.*t8.*tau_Hip.*2.4e+1+m_Body.*t4.*t12.*tau_Hip.*7.2e+1+m_Leg.*t4.*t8.*tau_Hip.*7.2e+1+m_Leg.*t4.*t12.*tau_Hip.*7.2e+1+f_Wrist_Bar.*l_Body.*l_Leg.*l_Wrist_Bar.*m_Body.*4.8e+1+f_Wrist_Bar.*l_Body.*l_Leg.*l_Wrist_Bar.*m_Leg.*6.0e+1+f_Wrist_Bar.*l_Leg.*m_Leg.*t8.*t18.*1.8e+1+f_Wrist_Bar.*l_Leg.*m_Leg.*t12.*t18.*1.8e+1+l_Body.*l_Leg.*m_Leg.*t20.*tau_Hip.*1.8e+1-l_Body.*l_Wrist_Bar.*m_Body.*t4.*tau_Hip.*7.2e+1-l_Body.*l_Wrist_Bar.*m_Leg.*t4.*tau_Hip.*1.44e+2-l_Leg.*l_Wrist_Bar.*m_Leg.*t20.*tau_Hip.*1.8e+1+l_Leg.*m_Body.*m_Leg.*t7.*t9.*2.5e+1-l_Leg.*m_Body.*m_Leg.*t7.*t13.*6.0e+1-g.*l_Leg.*t3.*t8.*t14.*1.6e+1-g.*l_Leg.*t3.*t8.*t15.*1.2e+1-g.*l_Leg.*t3.*t12.*t14.*4.8e+1-g.*l_Leg.*t3.*t12.*t15.*1.2e+1+l_Body.*l_Leg.*t7.*t12.*t14.*7.2e+1+l_Body.*l_Leg.*t7.*t12.*t15.*3.6e+1-l_Leg.*l_Wrist_Bar.*t7.*t8.*t14.*4.0e+1-l_Leg.*l_Wrist_Bar.*t7.*t8.*t15.*3.6e+1+t2.*t6.*t8.*t10.*t15.*6.0+t2.*t7.*t8.*t10.*t15.*6.0+t2.*t6.*t10.*t12.*t15.*6.0+t2.*t7.*t10.*t12.*t15.*6.0-l_Leg.*m_Body.*m_Leg.*t7.*t9.*t18.*3.0-l_Body.*l_Wrist_Bar.*t2.*t6.*t10.*t15.*1.2e+1-l_Body.*l_Wrist_Bar.*t2.*t7.*t10.*t15.*1.2e+1+m_Body.*m_Leg.*t2.*t6.*t8.*t10.*8.0+m_Body.*m_Leg.*t2.*t7.*t8.*t10.*8.0+m_Body.*m_Leg.*t2.*t6.*t10.*t12.*2.4e+1+m_Body.*m_Leg.*t2.*t7.*t10.*t12.*2.4e+1-f_Wrist_Bar.*l_Body.*l_Leg.*l_Wrist_Bar.*m_Leg.*t18.*3.6e+1+g.*l_Body.*l_Leg.*l_Wrist_Bar.*t3.*t14.*4.8e+1+g.*l_Body.*l_Leg.*l_Wrist_Bar.*t3.*t15.*2.4e+1-g.*l_Leg.*m_Body.*m_Leg.*t3.*t8.*4.0e+1-g.*l_Leg.*m_Body.*m_Leg.*t3.*t12.*6.0e+1+dth_Hip.*dth_Wrist.*t2.*t8.*t10.*t15.*1.2e+1+dth_Hip.*dth_Wrist.*t2.*t10.*t12.*t15.*1.2e+1+l_Body.*l_Leg.*m_Body.*m_Leg.*t7.*t12.*1.35e+2-l_Leg.*l_Wrist_Bar.*m_Body.*m_Leg.*t7.*t8.*1.0e+2-dl_Wrist_Bar.*dth_Wrist.*l_Leg.*m_Body.*m_Leg.*t8.*t20.*6.0+g.*l_Body.*l_Leg.*l_Wrist_Bar.*m_Body.*m_Leg.*t3.*9.0e+1-dth_Hip.*dth_Wrist.*l_Body.*l_Wrist_Bar.*t2.*t10.*t15.*2.4e+1+dth_Hip.*dth_Wrist.*m_Body.*m_Leg.*t2.*t8.*t10.*1.6e+1+dth_Hip.*dth_Wrist.*m_Body.*m_Leg.*t2.*t10.*t12.*4.8e+1+g.*l_Leg.*m_Body.*m_Leg.*t3.*t8.*t18.*1.2e+1-g.*l_Leg.*m_Body.*m_Leg.*t5.*t8.*t20.*3.0-l_Body.*l_Leg.*m_Body.*m_Leg.*t7.*t12.*t18.*9.0-l_Body.*l_Wrist_Bar.*m_Body.*m_Leg.*t2.*t6.*t10.*2.4e+1-l_Body.*l_Wrist_Bar.*m_Body.*m_Leg.*t2.*t7.*t10.*2.4e+1+l_Leg.*l_Wrist_Bar.*m_Body.*m_Leg.*t7.*t8.*t18.*1.2e+1+dl_Wrist_Bar.*dth_Wrist.*l_Body.*l_Leg.*l_Wrist_Bar.*m_Body.*m_Leg.*t20.*1.8e+1-dth_Hip.*dth_Wrist.*l_Body.*l_Wrist_Bar.*m_Body.*m_Leg.*t2.*t10.*4.8e+1-g.*l_Body.*l_Leg.*l_Wrist_Bar.*m_Body.*m_Leg.*t3.*t18.*1.8e+1+g.*l_Body.*l_Leg.*l_Wrist_Bar.*m_Body.*m_Leg.*t5.*t20.*9.0).*(-1.0./2.0))./(t8.*t14.*8.0+t8.*t15.*6.0+t12.*t14.*2.4e+1+t12.*t15.*6.0-l_Body.*l_Wrist_Bar.*t14.*2.4e+1-l_Body.*l_Wrist_Bar.*t15.*1.2e+1+m_Body.*m_Leg.*t8.*2.0e+1+m_Body.*m_Leg.*t12.*3.0e+1-l_Body.*l_Wrist_Bar.*m_Body.*m_Leg.*4.5e+1-m_Body.*m_Leg.*t8.*t18.*6.0+l_Body.*l_Wrist_Bar.*m_Body.*m_Leg.*t18.*9.0);
if nargout > 1
    t22 = l_Body.*l_Wrist_Bar.*t15.*6.0;
    t24 = l_Body.*l_Wrist_Bar.*t14.*1.2e+1;
    t26 = m_Body.*m_Leg.*t8.*1.3e+1;
    t27 = m_Body.*m_Leg.*t12.*1.5e+1;
    t28 = -t23;
    t29 = t8.*t14.*4.0;
    t30 = t8.*t15.*3.0;
    t31 = t12.*t15.*3.0;
    t33 = t12.*t14.*1.2e+1;
    t25 = -t22;
    t32 = -t24;
    t34 = m_Body.*m_Leg.*t8.*t19.*6.0;
    t35 = l_Body.*l_Wrist_Bar.*m_Body.*m_Leg.*t19.*9.0;
    t36 = -t34;
    t37 = t25+t26+t27+t28+t29+t30+t31+t32+t33+t35+t36;
    t38 = 1.0./t37;
    ddth_Wrist = t21.*t38.*(l_Leg.*m_Body.*tau_Hip.*2.4e+1+l_Leg.*m_Leg.*tau_Hip.*6.0+l_Body.*m_Body.*t2.*tau_Hip.*3.6e+1+l_Body.*m_Leg.*t2.*tau_Hip.*3.6e+1+l_Leg.*m_Leg.*t19.*tau_Hip.*1.8e+1-l_Wrist_Bar.*m_Body.*t2.*tau_Hip.*3.6e+1-l_Wrist_Bar.*m_Leg.*t2.*tau_Hip.*3.6e+1-dl_Wrist_Bar.*dth_Wrist.*l_Body.*l_Leg.*t14.*2.4e+1-dl_Wrist_Bar.*dth_Wrist.*l_Body.*l_Leg.*t15.*1.2e+1+dl_Wrist_Bar.*dth_Wrist.*l_Leg.*l_Wrist_Bar.*t14.*4.8e+1+dl_Wrist_Bar.*dth_Wrist.*l_Leg.*l_Wrist_Bar.*t15.*1.2e+1-f_Wrist_Bar.*l_Body.*l_Leg.*m_Leg.*t20.*9.0+f_Wrist_Bar.*l_Leg.*l_Wrist_Bar.*m_Leg.*t20.*9.0-g.*l_Body.*l_Leg.*t5.*t14.*1.2e+1-g.*l_Body.*l_Leg.*t5.*t15.*6.0+g.*l_Leg.*l_Wrist_Bar.*t5.*t14.*2.4e+1+g.*l_Leg.*l_Wrist_Bar.*t5.*t15.*6.0-l_Body.*t4.*t6.*t10.*t15.*3.0-l_Body.*t4.*t7.*t10.*t15.*3.0+l_Wrist_Bar.*t4.*t6.*t10.*t15.*3.0+l_Wrist_Bar.*t4.*t7.*t10.*t15.*3.0-l_Body.*m_Body.*m_Leg.*t4.*t6.*t10.*1.2e+1-l_Body.*m_Body.*m_Leg.*t4.*t7.*t10.*1.2e+1-l_Leg.*m_Body.*m_Leg.*t7.*t8.*t20.*(9.0./2.0)+l_Wrist_Bar.*m_Body.*m_Leg.*t4.*t6.*t10.*1.2e+1+l_Wrist_Bar.*m_Body.*m_Leg.*t4.*t7.*t10.*1.2e+1-dl_Wrist_Bar.*dth_Wrist.*l_Body.*l_Leg.*m_Body.*m_Leg.*5.4e+1+dl_Wrist_Bar.*dth_Wrist.*l_Leg.*l_Wrist_Bar.*m_Body.*m_Leg.*6.0e+1-g.*l_Body.*l_Leg.*m_Body.*m_Leg.*t5.*2.7e+1+g.*l_Leg.*l_Wrist_Bar.*m_Body.*m_Leg.*t5.*3.0e+1-dth_Hip.*dth_Wrist.*l_Body.*t4.*t10.*t15.*6.0+dth_Hip.*dth_Wrist.*l_Wrist_Bar.*t4.*t10.*t15.*6.0+dl_Wrist_Bar.*dth_Wrist.*l_Body.*l_Leg.*m_Body.*m_Leg.*t19.*1.8e+1-dth_Hip.*dth_Wrist.*l_Body.*m_Body.*m_Leg.*t4.*t10.*2.4e+1+dth_Hip.*dth_Wrist.*l_Wrist_Bar.*m_Body.*m_Leg.*t4.*t10.*2.4e+1+g.*l_Body.*l_Leg.*m_Body.*m_Leg.*t5.*t19.*9.0+l_Body.*l_Leg.*l_Wrist_Bar.*m_Body.*m_Leg.*t7.*t20.*(9.0./2.0)).*(-1.0./2.0);
end
if nargout > 2
    ddth_Hip = (t38.*(t8.*t14.*tau_Hip.*2.4e+1+t8.*t15.*tau_Hip.*7.2e+1+t10.*t15.*tau_Hip.*6.0+t12.*t14.*tau_Hip.*7.2e+1+t12.*t15.*tau_Hip.*7.2e+1-l_Body.*l_Wrist_Bar.*t14.*tau_Hip.*7.2e+1-l_Body.*l_Wrist_Bar.*t15.*tau_Hip.*1.44e+2+m_Body.*m_Leg.*t8.*tau_Hip.*9.6e+1+m_Body.*m_Leg.*t10.*tau_Hip.*2.4e+1+m_Body.*m_Leg.*t12.*tau_Hip.*1.44e+2+t10.*t15.*t19.*tau_Hip.*1.8e+1-dl_Wrist_Bar.*dth_Wrist.*l_Body.*t10.*t16.*1.2e+1+dl_Wrist_Bar.*dth_Wrist.*l_Wrist_Bar.*t10.*t16.*1.2e+1-l_Body.*l_Wrist_Bar.*m_Body.*m_Leg.*tau_Hip.*2.16e+2-f_Wrist_Bar.*l_Body.*t10.*t15.*t20.*9.0-f_Wrist_Bar.*l_Leg.*t4.*t8.*t15.*3.6e+1-f_Wrist_Bar.*l_Leg.*t4.*t12.*t15.*3.6e+1+f_Wrist_Bar.*l_Wrist_Bar.*t10.*t15.*t20.*9.0-g.*l_Body.*t5.*t10.*t16.*6.0+g.*l_Wrist_Bar.*t5.*t10.*t16.*6.0+l_Body.*l_Leg.*t2.*t15.*tau_Hip.*7.2e+1-l_Leg.*l_Wrist_Bar.*t2.*t15.*tau_Hip.*7.2e+1-l_Body.*t4.*t6.*t11.*t16.*3.0-l_Body.*t4.*t7.*t11.*t16.*3.0+l_Wrist_Bar.*t4.*t6.*t11.*t16.*3.0+l_Wrist_Bar.*t4.*t7.*t11.*t16.*3.0-l_Body.*m_Body.*t4.*t6.*t11.*t15.*1.2e+1-l_Body.*m_Body.*t4.*t7.*t11.*t15.*1.2e+1-l_Leg.*m_Body.*t4.*t7.*t9.*t15.*1.8e+1-l_Leg.*m_Leg.*t4.*t7.*t9.*t14.*6.0+l_Wrist_Bar.*m_Body.*t4.*t6.*t11.*t15.*1.2e+1+l_Wrist_Bar.*m_Body.*t4.*t7.*t11.*t15.*1.2e+1-m_Body.*t6.*t8.*t10.*t15.*t20.*6.0-m_Body.*t7.*t8.*t10.*t15.*t20.*(2.1e+1./2.0)-dl_Wrist_Bar.*dth_Wrist.*l_Body.*m_Body.*t10.*t15.*5.4e+1-dl_Wrist_Bar.*dth_Wrist.*l_Body.*m_Leg.*t10.*t14.*2.4e+1+dl_Wrist_Bar.*dth_Wrist.*l_Wrist_Bar.*m_Body.*t10.*t15.*6.0e+1+dl_Wrist_Bar.*dth_Wrist.*l_Wrist_Bar.*m_Leg.*t10.*t14.*4.8e+1-dth_Hip.*dth_Wrist.*l_Body.*t4.*t11.*t16.*6.0+dth_Hip.*dth_Wrist.*l_Wrist_Bar.*t4.*t11.*t16.*6.0+f_Wrist_Bar.*l_Body.*l_Leg.*l_Wrist_Bar.*t4.*t15.*7.2e+1-f_Wrist_Bar.*l_Leg.*m_Body.*m_Leg.*t4.*t8.*1.2e+1-f_Wrist_Bar.*l_Leg.*m_Body.*m_Leg.*t4.*t12.*3.6e+1+l_Body.*l_Leg.*m_Body.*m_Leg.*t2.*tau_Hip.*7.2e+1-l_Leg.*l_Wrist_Bar.*m_Body.*m_Leg.*t2.*tau_Hip.*7.2e+1-g.*l_Body.*m_Body.*t5.*t10.*t15.*2.7e+1-g.*l_Body.*m_Leg.*t5.*t10.*t14.*1.2e+1+g.*l_Wrist_Bar.*m_Body.*t5.*t10.*t15.*3.0e+1+g.*l_Wrist_Bar.*m_Leg.*t5.*t10.*t14.*2.4e+1+f_Wrist_Bar.*l_Body.*l_Leg.*l_Wrist_Bar.*m_Body.*m_Leg.*t4.*3.6e+1+dl_Wrist_Bar.*dth_Wrist.*l_Body.*m_Body.*t10.*t15.*t19.*1.8e+1-dl_Wrist_Bar.*dth_Wrist.*l_Leg.*m_Body.*t2.*t8.*t15.*1.2e+1-dl_Wrist_Bar.*dth_Wrist.*l_Leg.*m_Leg.*t2.*t8.*t14.*1.2e+1-dth_Hip.*dth_Wrist.*l_Body.*m_Body.*t4.*t11.*t15.*2.4e+1+dth_Hip.*dth_Wrist.*l_Wrist_Bar.*m_Body.*t4.*t11.*t15.*2.4e+1-dth_Hip.*dth_Wrist.*m_Body.*t8.*t10.*t15.*t20.*1.2e+1+g.*l_Body.*m_Body.*t5.*t10.*t15.*t19.*9.0-g.*l_Leg.*m_Body.*t2.*t5.*t8.*t15.*6.0-g.*l_Leg.*m_Leg.*t2.*t5.*t8.*t14.*6.0-l_Body.*l_Leg.*m_Body.*t4.*t7.*t12.*t15.*1.8e+1-l_Body.*l_Leg.*m_Leg.*t4.*t7.*t12.*t14.*1.8e+1+l_Body.*l_Wrist_Bar.*m_Body.*t6.*t10.*t15.*t20.*9.0+l_Body.*l_Wrist_Bar.*m_Body.*t7.*t10.*t15.*t20.*(2.7e+1./2.0)+l_Leg.*l_Wrist_Bar.*m_Body.*t4.*t7.*t8.*t15.*3.6e+1+l_Leg.*l_Wrist_Bar.*m_Leg.*t4.*t7.*t8.*t14.*1.8e+1+dl_Wrist_Bar.*dth_Wrist.*l_Body.*l_Leg.*l_Wrist_Bar.*m_Body.*t2.*t15.*3.6e+1+dl_Wrist_Bar.*dth_Wrist.*l_Body.*l_Leg.*l_Wrist_Bar.*m_Leg.*t2.*t14.*3.6e+1+dth_Hip.*dth_Wrist.*l_Body.*l_Wrist_Bar.*m_Body.*t10.*t15.*t20.*1.8e+1+g.*l_Body.*l_Leg.*l_Wrist_Bar.*m_Body.*t2.*t5.*t15.*1.8e+1+g.*l_Body.*l_Leg.*l_Wrist_Bar.*m_Leg.*t2.*t5.*t14.*1.8e+1))./(m_Leg.*t10.*2.0);
end
