function [ddth_Wrist,ddth_Hip] = find_dd_Onbar_Debbug2(dth_Hip,dth_Wrist,l_Body,l_Leg,l_Wrist_Bar,m_Body,m_Leg,tau_Hip,th_Hip,th_Wrist)
%FIND_DD_ONBAR_DEBBUG2
%    [DDTH_WRIST,DDTH_HIP] = FIND_DD_ONBAR_DEBBUG2(DTH_HIP,DTH_WRIST,L_BODY,L_LEG,L_WRIST_BAR,M_BODY,M_LEG,TAU_HIP,TH_HIP,TH_WRIST)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    22-May-2021 00:11:29

t2 = cos(th_Hip);
t3 = cos(th_Wrist);
t4 = sin(th_Hip);
t5 = sin(th_Wrist);
t6 = dth_Hip.^2;
t7 = dth_Wrist.^2;
t8 = l_Body.^2;
t9 = l_Body.^3;
t10 = l_Leg.^2;
t11 = l_Leg.^3;
t12 = l_Wrist_Bar.^2;
t13 = l_Wrist_Bar.^3;
t14 = m_Leg.^2;
t15 = th_Hip.*2.0;
t19 = l_Body.*l_Wrist_Bar.*m_Body.*4.0;
t20 = l_Body.*l_Wrist_Bar.*m_Leg.*4.0;
t16 = cos(t15);
t17 = sin(t15);
t18 = m_Body.*t8;
t21 = t15+th_Wrist;
t23 = m_Leg.*t8.*2.0;
t24 = m_Body.*t12.*4.0;
t25 = m_Leg.*t12.*2.0;
t26 = -t19;
t27 = -t20;
t22 = sin(t21);
t28 = t16.*t20;
t29 = t16.*t23;
t30 = t16.*t25;
t31 = m_Leg.*t8.*t16.*-2.0;
t32 = m_Leg.*t12.*t16.*-2.0;
t33 = t18+t23+t24+t25+t26+t27+t28+t31+t32;
t34 = 1.0./t33;
ddth_Wrist = -(t34.*(l_Leg.*tau_Hip.*4.0+l_Body.*t2.*tau_Hip.*8.0-l_Wrist_Bar.*t2.*tau_Hip.*8.0-l_Body.*l_Leg.*m_Body.*t5.*2.0-l_Body.*l_Leg.*m_Leg.*t5.*2.0+l_Body.*l_Leg.*m_Leg.*t22.*2.0+l_Leg.*l_Wrist_Bar.*m_Body.*t5.*4.0+l_Leg.*l_Wrist_Bar.*m_Leg.*t5.*2.0-l_Leg.*l_Wrist_Bar.*m_Leg.*t22.*2.0+l_Leg.*t7.*t17.*t20-l_Body.*m_Leg.*t4.*t6.*t10.*2.0-l_Body.*m_Leg.*t4.*t7.*t10.*2.0-l_Leg.*m_Leg.*t7.*t8.*t17.*2.0-l_Leg.*m_Leg.*t7.*t12.*t17.*2.0+l_Wrist_Bar.*m_Leg.*t4.*t6.*t10.*2.0+l_Wrist_Bar.*m_Leg.*t4.*t7.*t10.*2.0-dth_Hip.*dth_Wrist.*l_Body.*m_Leg.*t4.*t10.*4.0+dth_Hip.*dth_Wrist.*l_Wrist_Bar.*m_Leg.*t4.*t10.*4.0))./l_Leg;
if nargout > 1
    ddth_Hip = (t34.*(t18.*tau_Hip.*4.0+m_Body.*t12.*tau_Hip.*1.6e+1+m_Leg.*t8.*tau_Hip.*1.6e+1+m_Leg.*t10.*tau_Hip.*4.0+m_Leg.*t12.*tau_Hip.*1.6e+1-l_Body.*l_Wrist_Bar.*m_Body.*tau_Hip.*1.6e+1-l_Body.*l_Wrist_Bar.*m_Leg.*tau_Hip.*3.2e+1-l_Body.*t5.*t10.*t14.*2.0+l_Wrist_Bar.*t5.*t10.*t14.*2.0+l_Body.*l_Leg.*m_Leg.*t2.*tau_Hip.*1.6e+1-l_Leg.*l_Wrist_Bar.*m_Leg.*t2.*tau_Hip.*1.6e+1-l_Body.*m_Body.*m_Leg.*t5.*t10.*2.0+l_Wrist_Bar.*m_Body.*m_Leg.*t5.*t10.*4.0-l_Leg.*m_Leg.*t2.*t5.*t18.*2.0+l_Leg.*m_Leg.*t3.*t4.*t18.*2.0+l_Leg.*m_Leg.*t2.*t5.*t19-l_Body.*t4.*t6.*t11.*t14.*2.0-l_Body.*t4.*t7.*t11.*t14.*2.0+l_Body.*t3.*t10.*t14.*t17.*2.0+l_Body.*t5.*t10.*t14.*t16.*2.0+l_Leg.*t3.*t4.*t8.*t14.*8.0+l_Leg.*t3.*t4.*t12.*t14.*8.0-l_Leg.*t4.*t7.*t9.*t14.*8.0+l_Leg.*t4.*t7.*t13.*t14.*8.0+l_Wrist_Bar.*t4.*t6.*t11.*t14.*2.0+l_Wrist_Bar.*t4.*t7.*t11.*t14.*2.0-l_Wrist_Bar.*t3.*t10.*t14.*t17.*2.0-l_Wrist_Bar.*t5.*t10.*t14.*t16.*2.0-t6.*t8.*t10.*t14.*t17.*2.0-t7.*t8.*t10.*t14.*t17.*4.0-t6.*t10.*t12.*t14.*t17.*2.0-t7.*t10.*t12.*t14.*t17.*4.0-l_Body.*l_Leg.*l_Wrist_Bar.*t3.*t4.*t14.*1.6e+1+l_Leg.*l_Wrist_Bar.*m_Leg.*t4.*t7.*t18.*1.0e+1+l_Leg.*m_Body.*m_Leg.*t3.*t4.*t12.*8.0-l_Leg.*m_Body.*m_Leg.*t4.*t7.*t9.*2.0+l_Leg.*m_Body.*m_Leg.*t4.*t7.*t13.*8.0-l_Body.*l_Leg.*t4.*t7.*t12.*t14.*2.4e+1+l_Body.*l_Wrist_Bar.*t6.*t10.*t14.*t17.*4.0+l_Body.*l_Wrist_Bar.*t7.*t10.*t14.*t17.*8.0+l_Leg.*l_Wrist_Bar.*t4.*t7.*t8.*t14.*2.4e+1-dth_Hip.*dth_Wrist.*l_Body.*t4.*t11.*t14.*4.0+dth_Hip.*dth_Wrist.*l_Wrist_Bar.*t4.*t11.*t14.*4.0-dth_Hip.*dth_Wrist.*t8.*t10.*t14.*t17.*4.0-dth_Hip.*dth_Wrist.*t10.*t12.*t14.*t17.*4.0+dth_Hip.*dth_Wrist.*l_Body.*l_Wrist_Bar.*t10.*t14.*t17.*8.0-l_Body.*l_Leg.*l_Wrist_Bar.*m_Body.*m_Leg.*t3.*t4.*8.0-l_Body.*l_Leg.*m_Body.*m_Leg.*t4.*t7.*t12.*1.6e+1))./(m_Leg.*t10);
end
