function ddtheta = find_ddtheta(Lc,M,Mtheta,g,theta)
%FIND_DDTHETA
%    DDTHETA = FIND_DDTHETA(LC,M,MTHETA,G,THETA)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    17-May-2021 15:39:51

ddtheta = (1.0./Lc.^2.*(Mtheta.*3.0-Lc.*M.*g.*sin(theta).*3.0))./(M.*4.0);
